version: '3.8'
services:
  store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zenith-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: zenith-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./zenith-store.dump:/docker-entrypoint-initdb.d/zenith-store.dump
    restart: always

volumes:
  postgres-data: